### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by greymag**
- Add error info on login failure
- Mute PlatformException on get profile

### CODE REVIEW

**Comment by MsXam** [comment]
Can we remove the UIWebView that this plugin uses for iOS and use WKWebView since UIWebView is deprecated and submissions to the app store will be rejected.

**Comment by greymag** [comment]
> Can we remove the UIWebView that this plugin uses for iOS and use WKWebView since UIWebView is deprecated and submissions to the app store will be rejected.

This plugin uses latest Facebook SDK 7.0. Facebook did replace UIWebView with WKWebView in version 5.5. In plugin code we also didn't use UIWebView. So this plugin shouldn't contains UIWebView. Is it? If it does - please create an issue.

**Comment by MsXam** [comment]
If you enable ISSUE submission on this project  I will raise an issue for you.

**Comment by greymag** [comment]
Oops =) done

**Pull request merged**
